### ISSUE TITLE
STELLA: Inconsistency between copy constructor and assignment operator

### ISSUE THREAD

**Issue by havogt** [GridTools/serialbox#79]
The interface for the Savepoint is inconsistent as the `operator=` is doing a deep copy while the copy constructor is doing a shallow copy. The reason is STELLA's `Init` pattern. We won't fix this. We keep this issue open as a reference in case someone runs into this problem.

thfabian:
> Just as a side node the problem with the copy constructor in `Savepoint` (due to Init patterm) is probably also present in all the other stella classes (`MetainfoSet` and `DataFieldInfo`).
> Maybe the proper solution would be to add an `assert` if `Init` has not been called and the user attempts to copy the object?

@thfabian @andyspiros Is this a correct summary of the issue? Maybe you can expand if you think there should be more info.

**Comment by andyspiros** [comment]
Fine for me.

**Comment by havogt** [comment]
STELLA is dead.

**Comment by andyspiros** [comment]
> STELLA is dead.

RIP STELLA, you have been a loyal friend, time to let you go definitively.
